Imports

In [47]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt

1-Reading Dataset from csv
2-Separating features coloumn and saving them in Variable X
3-separaring labels coloumn and saving it in Variable Y

In [48]:
dataset=pd.read_csv("stroke dataset.csv")
from sklearn.utils import resample
dataset=resample(dataset,replace=True,n_samples=15000,random_state=1)
print(dataset.head)
X=dataset.iloc[:,1:-1].values
Y=dataset.iloc[:,-1].values

<bound method NDFrame.head of          id  gender    age  hypertension  heart_disease ever_married  \
235    1210  Female  68.00             0              0          Yes   
3980  11192  Female  45.00             0              0          Yes   
905    9262  Female  31.00             0              0          Yes   
2763  72451  Female  45.00             0              0          Yes   
2895  56855    Male  46.00             0              0          Yes   
...     ...     ...    ...           ...            ...          ...   
817   25514    Male  12.00             0              0           No   
925   53538  Female   7.00             0              0           No   
1486   1405    Male   1.88             0              0           No   
3955   1737  Female  16.00             0              0           No   
3720  46292    Male  64.00             0              0          Yes   

     work_type Residence_type  avg_glucose_level   bmi smoking_status  stroke  
235    Private          R

1-filling null values if there is any , with SimpleImputer class and update the Variable X
2-Using Label Encoder class to change abscent and  present into 0,1 for better computations and training

In [49]:
from sklearn.preprocessing import LabelEncoder
EncodeClassLabels=LabelEncoder()
X1=EncodeClassLabels.fit_transform(X[:,[4]])
c=np.array(X1)
X[:,[4]]=c.reshape(len(c),1)

X2=EncodeClassLabels.fit_transform(X[:,[5]])
c2=np.array(X2)
X[:,[5]]=c2.reshape(len(c2),1)


X3=EncodeClassLabels.fit_transform(X[:,[6]])
c3=np.array(X3)
X[:,[6]]=c3.reshape(len(c3),1)


X4=EncodeClassLabels.fit_transform(X[:,[9]])
c4=np.array(X4)
X[:,[9]]=c4.reshape(len(c4),1)


X5=EncodeClassLabels.fit_transform(X[:,[0]])
c5=np.array(X5)
X[:,[0]]=c5.reshape(len(c5),1)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X = imputer.fit_transform(X)
print(X[:100])


[[0 68.0 0 0 1 2 0 211.06 39.3 0]
 [0 45.0 0 0 1 2 0 218.1 55.0 3]
 [0 31.0 0 0 1 2 0 76.26 35.6 2]
 [0 45.0 0 0 1 2 0 63.73 32.0 0]
 [1 46.0 0 0 1 2 1 137.77 29.3 2]
 [0 40.0 0 0 1 2 1 89.61 41.2 1]
 [0 72.0 1 0 1 2 1 221.79 30.0 2]
 [0 37.0 0 0 1 2 0 77.1 55.9 0]
 [0 73.0 0 0 1 2 0 98.34 30.9 0]
 [1 82.0 0 0 1 3 1 214.51 24.0 1]
 [1 80.0 0 0 0 3 0 204.17 41.3 1]
 [1 71.0 1 0 1 2 0 229.73 30.4 2]
 [0 70.0 1 0 1 3 0 154.6 28.5 1]
 [1 31.0 0 0 0 2 0 108.56 21.8 2]
 [0 70.0 0 0 1 2 0 69.04 35.9 1]
 [0 41.0 0 0 1 3 0 76.66 26.1 0]
 [0 3.0 0 0 0 4 0 79.76 15.6 0]
 [0 1.8 0 0 0 4 1 58.26 16.5 0]
 [0 23.0 0 0 0 2 0 95.66 19.9 3]
 [0 52.0 0 0 1 0 1 110.36 39.1 1]
 [0 1.16 0 0 0 4 1 60.98 17.2 0]
 [0 66.0 0 1 1 0 0 76.11 37.0 0]
 [0 35.0 0 0 1 2 1 87.72 21.3 2]
 [0 32.0 0 0 0 2 0 199.18 27.9 2]
 [0 44.0 0 0 1 2 0 90.4 33.1 1]
 [1 41.0 1 0 1 2 1 69.52 31.9 2]
 [0 41.0 0 0 0 2 1 76.08 25.1 2]
 [1 32.0 0 0 1 2 0 70.96 33.1 0]
 [1 45.0 1 0 1 3 0 239.19 52.5 0]
 [1 63.0 0 0 1 2 0 77.82 30.3 0]
 [0 

C:\Users\usama\Desktop\AVND_Model\venv\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


splitting the data

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)



Parameters value of model for cross validation

In [51]:
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 80, num = 10)]
# # Number of features to consider at every split
# max_features = ['auto', 'sqrt']
# # Maximum number of levels in tree
# max_depth = [2,4]
# # Minimum number of samples required to split a node
# min_samples_split = [2, 5]
# # Minimum number of samples required at each leaf node
# min_samples_leaf = [1, 2]
# # Method of selecting samples for training each tree
# bootstrap = [True, False]
#
# params={'n_estimators': n_estimators,
#                'max_depth': max_depth,
#                'min_samples_split': min_samples_split,
#                'min_samples_leaf': min_samples_leaf,}
# print(params)

learn_rate = [ 0.1, 0.2, 0.3,1]
momentum = [0.0, 0.2, 0.4, 0.6, 0.8, 0.9]
param_grid=dict(learning_rate=learn_rate,n_estimators=n_estimators)

Transforming the values into range of values like -1 to 1 for better training

In [52]:
# from sklearn.preprocessing import StandardScaler
# ss=StandardScaler()
# x_train=ss.fit_transform(x_train)
# x_test=ss.transform(x_test)

initializing randomforestclassifier
applying GridSearchCV(cross-validation)
and training using fit method

In [53]:
from sklearn.ensemble import RandomForestClassifier as RFC
Mode=RFC(n_estimators=20,criterion="entropy")
from sklearn.ensemble import  AdaBoostClassifier
Model=AdaBoostClassifier(base_estimator=Mode)
from sklearn.model_selection import GridSearchCV
rfc=GridSearchCV(estimator=Model,param_grid =param_grid , cv = 3, verbose=2, n_jobs = 4)
rfc.fit(x_train,y_train)


Fitting 3 folds for each of 40 candidates, totalling 120 fits


GridSearchCV(cv=3,
             estimator=AdaBoostClassifier(base_estimator=RandomForestClassifier(criterion='entropy',
                                                                                n_estimators=20)),
             n_jobs=4,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 1],
                         'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72,
                                          80]},
             verbose=2)

making prediction on test data

In [54]:
y_pred=rfc.predict(x_test)

checking accuracy using accuracy_score

In [55]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
print(ac)

0.9956666666666667


In [56]:

# import joblib
# model=joblib.load("stroke.sav")

In [57]:
# p = model.predict([[0,38,2,1,20,0,0,1,0,221,140,90,21.35,95,70]])
#
# print(p)
#
# # 0,63,1,0,0,0,0,0,0,205,138,71,33.11,60,85,1
# # 0,45,2,1,20,0,0,0,0,313,100,71,21.68,79,78,0
# # 0,38,2,1,20,0,0,1,0,221,140,90,21.35,95,70,1
# # 1,48,3,1,10,0,0,1,0,232,138,90,22.37,64,72,0
# # 0,46,2,1,20,0,0,0,0,291,112,78,23.38,80,89,1
# # 0,38,2,1,5,0,0,0,0,195,122,84.5,23.24,75,78,0
# # 1,41,2,0,0,0,0,0,0,195,139,88,26.88,85,65,0
# # 0,42,2,1,30,0,0,0,0,190,108,70.5,21.59,72,85,0
# # 0,43,1,0,0,0,0,0,0,185,123.5,77.5,29.89,70,NA,0

In [59]:
 import joblib
joblib.dump(rfc,"stroke.sav")

['stroke.sav']